y = a.x+b
y burada tahmin etmeye çalıştığımız bağımlı değişkendir
x bağımsız değişkendir
b, y kesme noktasıdır, yeni x 0 oldugunda y'nin değeridir.
a, x'teki bir birimlik değişiklik için y'deki değişikliği temsil eden doğrunun eğimidir.


Numpy ile Veri Oluşturma

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interactive

np.random.seed(42)

In [ ]:
x = 2 * np.random.rand(100,1) 
y = 3 * x + 4 + np.random.randn(100,1) #3x + 4

In [ ]:
plt.scatter(x, y, label='Data points' , color='blue')
plt.plot(x,3 * x + 4, label="Equation", color='red')
plt.legend()
plt.show()

In [ ]:
def plot_func(a,b):
    plt.scatter(x, y, label='Data points' , color='blue')
    plt.plot(x,a * x + b, label="Equation", color='red')
    plt.xlabel('x',fontsize=16)
    plt.ylabel('y',fontsize=16)
    plt.title(f'y = {a:.2f} * x + {b:.2f}', fontsize=20)
    plt.legend()
    plt.show()

In [ ]:
interactive(plot_func ,a=(-5,5,0.1) , b=(-5,5,0.1))

## Sklearn Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [ ]:
model.fit(x, y)

In [14]:
model.coef_, model.intercept_

(array([[2.77011339]]), array([4.21509616]))

In [13]:
model.predict([[1]])

array([[6.98520954]])

In [12]:
x_input = 1 # modellnen denklem a * x + b
# a = model.coef_
# b = model.intercept_
model.coef_ * x_input + model.intercept_

array([[6.98520954]])

In [20]:
#np.linalg.lstsq(x, y, rcond=None) sklerarn kaynak kodunda bu kullanılıyor

## Ev fiyatları data seti yüklenmesi ve Linear Regression uygulanması

In [ ]:
from sklearn.datasets import fetch_openml
housing = fetch_openml(name='house_prices', as_frame=True)


dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [18]:
X = housing.data
y = housing.target
X

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub  ...           0        0    NaN    NaN   
1            Lvl    AllPub  ...           0        0    NaN    NaN   
2            Lvl    AllPub  ...           0        0    NaN    NaN   
3            Lvl    AllPub  ...           0        0    NaN    NaN   
4            Lvl    AllPub  ...           0        0    NaN    NaN   
...          ...       ...  ...         ...      ...    ...    ...   
1455         Lvl    AllPub  ...           0        0    NaN    NaN   
1456         Lvl    AllPub  ...           0        0    NaN  MnPrv   
1457         Lvl    AllPub  ...           0        0    NaN  GdPrv   
1458         Lvl    AllPub  ...           0        0    NaN    NaN   
1459         Lvl    AllPub  ...           0        0    NaN    NaN   

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0            NaN       0      2    2008        WD         Normal  
1            NaN       0      5    2007        WD         Normal  
2            NaN       0      9    2008        WD         Normal  
3            NaN       0      2    2006        WD        Abnorml  
4            NaN       0     12    2008        WD         Normal  
...          ...     ...    ...     ...       ...            ...  
1455         NaN       0      8    2007        WD         Normal  
1456         NaN       0      2    2010        WD         Normal  
1457        Shed    2500      5    2010        WD         Normal  
1458         NaN       0      4    2010        WD         Normal  
1459         NaN       0      6    2008        WD         Normal  

[1460 rows x 80 columns]

0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64